{
    'name': 'ZENLENET 运营',
    'version': '19.0.2.1.0',
    'category': 'Sales',
    'summary': '数据中心、线路、IP；客户、报价、合同、出账；业务流转与工单',
    'author': 'ZENLENET PTE. LTD.',
    'license': 'LGPL-3',
    'depends': ['contacts', 'sale_management', 'account', 'mail', 'auth_oauth'],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/flow_sequence.xml',
        'data/cron.xml',
        'data/oauth_provider.xml',
        'reports/report_templates.xml',
        'views/maintenance_views.xml',
        'views/partner_views.xml',
        'views/order_views.xml',
        'views/invoice_views.xml',
        'views/contract_views.xml',
        'views/datacenter_views.xml',
        'views/address_views.xml',
        'views/ipset_views.xml',
        'views/line_views.xml',
        'views/return_views.xml',
        'views/notice_views.xml',
        'views/flow_views.xml',
        'views/ticket_views.xml',
        'views/purchase_views.xml',
        'views/asset_views.xml',
        'views/settings_views.xml',
        'views/config_views.xml',
        'views/home_views.xml',
        'views/menus.xml',
        'data/shell.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'zenlenet_ops/static/src/scss/zenlenet.scss',
        ],
    },
    'installable': True,
    'application': True,
}
